name: Run Tests
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup nodeJs
        uses: actions/setup-node@v2
        with: 
          node_version: '14'
      - name: Install dependencies
        run: npm install
      - name: Run tesst
        run: npm test
